title: GitHub Copilot Prompt Library
description: A comprehensive collection of prompts for different roles in software development
remote_theme: just-the-docs/just-the-docs

# Add required plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

url: https://Parul-mahajan.github.io/Prompt-Library

aux_links:
  "View on GitHub":
    - "https://github.com/Parul-mahajan/Prompt-Library"

# Enable search
search_enabled: true

# Optimize search engine
search:
  # Split pages into sections
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Navigation
nav:
  - title: AI/ML Development
    url: /AI_MLDevelopment/
    children:
      - title: Preprocessing Data
        url: /AI_MLDevelopment/PreprocessingData/
      - title: Writing Training Scripts
        url: /AI_MLDevelopment/WritingTrainingScripts/
  - title: Best Practices
    url: /BestPractices/
    children:
      - title: Code Review Best Practices
        url: /BestPractices/CodeReviewBestPractices/
        children:
          - title: Adherence to Standards
            url: /BestPractices/CodeReviewBestPractices/AdherenceToStandards/
          - title: Handling Auto-Generated Code
            url: /BestPractices/CodeReviewBestPractices/HandlingAutoGeneratedCode/
          - title: Identifying Potential Bugs
            url: /BestPractices/CodeReviewBestPractices/IdentifyingPotentialBugs/
          - title: Suggesting Improvements
            url: /BestPractices/CodeReviewBestPractices/SuggestingImprovements/
      - title: Prompt Engineering Best Practices
        url: /BestPractices/PromptEngineeringBestPractices/
        children:
          - title: Copilot Chat Patterns
            url: /BestPractices/PromptEngineeringBestPractices/CopilotChatPatterns/
          - title: Different Prompting Techniques
            url: /BestPractices/PromptEngineeringBestPractices/DifferentPromptingTechniques/
          - title: GitHub Copilot Specific Techniques
            url: /BestPractices/PromptEngineeringBestPractices/GitHubCopilotSpecificTechniques/
          - title: Git Integration Practices
            url: /BestPractices/PromptEngineeringBestPractices/GitIntegrationPractices/
          - title: How to Write a Good Prompt
            url: /BestPractices/PromptEngineeringBestPractices/HowToWriteAGoodPrompt/
          - title: IDE Specific Features and Resources
            url: /BestPractices/PromptEngineeringBestPractices/IDESpecificFeaturesAndResources/
      - title: Security Best Practices
        url: /BestPractices/SecurityBestPractices/
        children:
          - title: Identifying Security Vulnerabilities
            url: /BestPractices/SecurityBestPractices/IdentifyingSecurityVulnerabilities/
          - title: Secure Configurations
            url: /BestPractices/SecurityBestPractices/SecureConfigurations/
          - title: Writing Secure Code
            url: /BestPractices/SecurityBestPractices/WritingSecureCode/
  - title: Code Optimization
    url: /CodeOptimization/
    children:
      - title: Efficiency
        url: /CodeOptimization/Efficiency/
      - title: Performance Bottlenecks
        url: /CodeOptimization/PerformanceBottlenecks/
      - title: Performance Optimization Patterns
        url: /CodeOptimization/PerformanceOptimizationPatterns/
      - title: Refactoring
        url: /CodeOptimization/Refactoring/
  - title: Designer Resources
    url: /Designer/
    children:
      - title: Design
        url: /Designer/Design
      - title: Development
        url: /Designer/Development
      - title: Testing
        url: /Designer/Testing
      - title: Deployment
        url: /Designer/Deployment
      - title: Maintenance
        url: /Designer/Maintenance
  - title: Developer Resources
    url: /Developer/
    children:
      - title: Design
        url: /Developer/Design
      - title: Development
        url: /Developer/Development
      - title: Testing
        url: /Developer/Testing
      - title: Deployment
        url: /Developer/Deployment
      - title: Maintenance
        url: /Developer/Maintenance
  - title: DevOps Practices
    url: /DevOpsEngineer/
    children:
      - title: CI/CD Pipeline Configuration
        url: /DevOpsEngineer/CICDPipelineConfiguration
      - title: Design
        url: /DevOpsEngineer/Design
      - title: Testing
        url: /DevOpsEngineer/Testing
      - title: Deployment
        url: /DevOpsEngineer/Deployment
      - title: Maintenance
        url: /DevOpsEngineer/Maintenance
  - title: Documentation Prompts
    url: /DocumentationPrompts/
    children:
      - title: Documenting Code with Inline Comments
        url: /DocumentationPrompts/DocumentingCodeWithInlineComments
      - title: Generating README
        url: /DocumentationPrompts/GeneratingREADME
      - title: Writing API Documentation
        url: /DocumentationPrompts/WritingAPIDocumentation
  - title: Learning Resources
    url: /LearningResources/
    children:
      - title: Explaining Complex Code Snippets
        url: /LearningResources/ExplainingComplexCodeSnippets
      - title: Generating Tutorials
        url: /LearningResources/GeneratingTutorials
      - title: Onboarding New Team Members
        url: /LearningResources/OnboardingNewTeamMembers
  - title: Product Manager Tools
    url: /ProductManager/
    children:
      - title: Requirements
        url: /ProductManager/Requirements
      - title: Design
        url: /ProductManager/Design
      - title: Testing
        url: /ProductManager/Testing
      - title: Deployment
        url: /ProductManager/Deployment
      - title: Maintenance
        url: /ProductManager/Maintenance
  - title: Stored Procedures
    url: /StoredProcedures/
    children:
      - title: Creating
        url: /StoredProcedures/Creating
      - title: Debugging
        url: /StoredProcedures/Debugging
      - title: Optimizing
        url: /StoredProcedures/Optimizing
  - title: Testing
    url: /Testing/
    children:
      - title: Tester Resources
        url: /Testing/Tester/Testing
      - title: Testing Enhancements
        url: /Testing/TestingEnhancements/AutomationManualTestCases
  - title: Troubleshooting Prompts
    url: /TroubleshootingPrompts/
    children:
      - title: Debugging Runtime Errors
        url: /TroubleshootingPrompts/DebuggingRuntimeErrors
      - title: Error Handling Patterns
        url: /TroubleshootingPrompts/ErrorHandlingPatterns
      - title: Identifying Performance Bottlenecks
        url: /TroubleshootingPrompts/IdentifyingPerformanceBottlenecks
      - title: Resolving Dependency Conflicts
        url: /TroubleshootingPrompts/ResolvingDependencyConflicts

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/Parul-mahajan/Prompt-Library
    hide_icon: false 

# Color scheme
color_scheme: dark

# Enable copy code buttons
enable_copy_code_button: true

# Collection configurations
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
