# Updated navigation structure to match the reference image
nav:
  - title: Home
    url: /
  - title: Configuration
    url: /Configuration/
  - title: UI Components
    url: /UIComponents/
    children:
      - title: Buttons
        url: /UIComponents/Buttons/
      - title: Forms
        url: /UIComponents/Forms/
  - title: Utilities
    url: /Utilities/
    children:
      - title: Colors
        url: /Utilities/Colors/
      - title: Typography
        url: /Utilities/Typography/
  - title: Layout
    url: /Layout/
    children:
      - title: Grid
        url: /Layout/Grid/
      - title: Spacing
        url: /Layout/Spacing/
  - title: Navigation
    url: /Navigation/
    children:
      - title: Main Navigation
        url: /Navigation/MainNavigation/
      - title: Auxiliary Links
        url: /Navigation/AuxiliaryLinks/
      - title: Breadcrumbs
        url: /Navigation/Breadcrumbs/
      - title: Child Pages
        url: /Navigation/ChildPages/
      - title: In-Page Navigation
        url: /Navigation/InPageNavigation/