site_name: Prompt Library
site_description: A comprehensive library of prompts for AI and development
site_author: Cognizant
repo_url: https://github.com/Parul-mahajan/Prompt-Library
site_url: https://parul-mahajan.github.io/Prompt-Library/
edit_uri: edit/main/
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light_blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep_purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
  - tags

nav:
  - Home: index.md
  - AI_MLDevelopment:
      - Preprocessing Data: AI_MLDevelopment/PreprocessingData.md
      - Writing Training Scripts: AI_MLDevelopment/WritingTrainingScripts.md
  - Best_Practices:
      - Code_Review_Best_Practices:
          - Adherence To Standards: BestPractices/CodeReviewBestPractices/AdherenceToStandards.md
          - Handling Auto-Generated Code: BestPractices/CodeReviewBestPractices/HandlingAutoGeneratedCode.md
          - Identifying Potential Bugs: BestPractices/CodeReviewBestPractices/IdentifyingPotentialBugs.md
          - Suggesting Improvements: BestPractices/CodeReviewBestPractices/SuggestingImprovements.md
      - Prompt_Engineering_Best_Practices:
          - Copilot Chat Patterns: BestPractices/PromptEngineeringBestPractices/CopilotChatPatterns.md
          - Different Prompting Techniques: BestPractices/PromptEngineeringBestPractices/DifferentPromptingTechniques.md
          - GitHub Copilot Specific Techniques: BestPractices/PromptEngineeringBestPractices/GitHubCopilotSpecificTechniques.md
          - Git Integration Practices: BestPractices/PromptEngineeringBestPractices/GitIntegrationPractices.md
          - How To Write A Good Prompt: BestPractices/PromptEngineeringBestPractices/HowToWriteAGoodPrompt.md
          - IDE Specific Features: BestPractices/PromptEngineeringBestPractices/IDESpecificFeaturesAndResources.md
      - Security_Best_Practices:
          - Identifying Security Vulnerabilities: BestPractices/SecurityBestPractices/IdentifyingSecurityVulnerabilities.md
          - Secure Configurations: BestPractices/SecurityBestPractices/SecureConfigurations.md
          - Writing Secure Code: BestPractices/SecurityBestPractices/WritingSecureCode.md
  - Code_Optimization:
      - Efficiency: CodeOptimization/Efficiency.md
      - Performance Bottlenecks: CodeOptimization/PerformanceBottlenecks.md
      - Performance Optimization Patterns: CodeOptimization/PerformanceOptimizationPatterns.md
      - Refactoring: CodeOptimization/Refactoring.md
  - Designer:
      - Requirements: Designer/Requirements.md
      - Design: Designer/Design.md
      - Development: Designer/Development.md
      - Testing: Designer/Testing.md
      - Deployment: Designer/Deployment.md
      - Maintenance: Designer/Maintenance.md
  - Developer:
      - Requirements: Developer/Requirements.md
      - Design: Developer/Design.md
      - Development: Developer/Development.md
      - Testing: Developer/Testing.md
      - Deployment: Developer/Deployment.md
      - Maintenance: Developer/Maintenance.md
  - DevOps_Engineer:
      - Requirements: DevOpsEngineer/Requirements.md
      - Design: DevOpsEngineer/Design.md
      - Development: DevOpsEngineer/Development.md
      - Testing: DevOpsEngineer/Testing.md
      - Deployment: DevOpsEngineer/Deployment.md
      - Maintenance: DevOpsEngineer/Maintenance.md
      - CI/CD Pipeline Configuration: DevOpsEngineer/CICDPipelineConfiguration.md
  - Documentation_Prompts:
      - Documenting Code With Inline Comments: DocumentationPrompts/DocumentingCodeWithInlineComments.md
      - Generating README: DocumentationPrompts/GeneratingREADME.md
      - Writing API Documentation: DocumentationPrompts/WritingAPIDocumentation.md
  - Learning_Resources:
      - Explaining Complex Code Snippets: LearningResources/ExplainingComplexCodeSnippets.md
      - Generating Tutorials: LearningResources/GeneratingTutorials.md
      - Onboarding New Team Members: LearningResources/OnboardingNewTeamMembers.md
  - Product_Manager:
      - Requirements: ProductManager/Requirements.md
      - Design: ProductManager/Design.md
      - Testing: ProductManager/Testing.md
      - Deployment: ProductManager/Deployment.md
  - Stored_Procedures:
      - Creating: StoredProcedures/Creating.md
      - Debugging: StoredProcedures/Debugging.md
      - Optimizing: StoredProcedures/Optimizing.md
  - Testing:
      - Tester:
          - Requirements: Testing/Tester/Requirements.md
          - Design: Testing/Tester/Design.md
          - Development: Testing/Tester/Development.md
          - Testing: Testing/Tester/Testing.md
          - Deployment: Testing/Tester/Deployment.md
          - Maintenance: Testing/Tester/Maintenance.md
      - Testing_Enhancements:
          - Unit Test Cases: Testing/TestingEnhancements/UnitTestCases.md
          - Automation Manual Test Cases: Testing/TestingEnhancements/AutomationManualTestCases.md
  - Troubleshooting_Prompts:
      - Debugging Runtime Errors: TroubleshootingPrompts/DebuggingRuntimeErrors.md
      - Error Handling Patterns: TroubleshootingPrompts/ErrorHandlingPatterns.md
      - Identifying Performance Bottlenecks: TroubleshootingPrompts/IdentifyingPerformanceBottlenecks.md
      - Resolving Dependency Conflicts: TroubleshootingPrompts/ResolvingDependencyConflicts.md
